import { PixelAssetGrid, PixelButton, PixelCommandBar, PixelEmptyState, PixelPanel } from "@jdsalasc/pixel-ui";
import type { AssetLibraryItemView, AssetLibraryPresetCompositionView, AssetLibraryPresetView } from "../domain/contracts.js";

interface AssetLibraryPanelProps { busy: boolean; online: boolean; restPort?: number; query: string; items: AssetLibraryItemView[]; presets: AssetLibraryPresetView[]; total: number; composition?: AssetLibraryPresetCompositionView | null; onQueryChange(query: string): void; onSearch(): void; onComposePreset?(id: string): void; }

export function AssetLibraryPanel({ busy, online, restPort, query, items, presets, total, composition, onQueryChange, onSearch, onComposePreset }: AssetLibraryPanelProps) {
  const previewBase = restPort ? `http://127.0.0.1:${restPort}/api/v1/library/items` : "";
  return <PixelPanel title="ASSET LIBRARY" accent="cyan"><p className="muted">Explora assets deterministas y presets de escenas sin cargar todo el catálogo en contexto.</p><div className="asset-library-search"><PixelCommandBar value={query} onValueChange={onQueryChange} placeholder="Search trees, dragons, rain..." aria-label="Search asset library" /><PixelButton tone="cyan" disabled={busy || !online} onClick={onSearch}>{busy ? "SEARCHING..." : "SEARCH LIBRARY"}</PixelButton></div>{presets.length ? <div className="asset-library-presets"><span className="eyebrow">PRESETS</span>{presets.map((preset) => <PixelButton key={preset.id} tone="cyan" disabled={busy || !online || !onComposePreset} onClick={() => onComposePreset?.(preset.id)} title={preset.description}>{preset.title}</PixelButton>)}</div> : null}{composition ? <p className="muted">PRESET READY · {composition.layers.map((layer) => `${layer.role}:${layer.assetId}`).join(" · ")}</p> : null}{items.length ? <PixelAssetGrid items={items.map((item) => ({ id: item.id, name: item.title, preview: previewBase ? `${previewBase}/${encodeURIComponent(item.id)}/preview` : undefined, detail: `${item.category} · ${item.variants.slice(0, 3).join(" · ")}`, status: <small>{item.kind.toUpperCase()}</small> }))} /> : <PixelEmptyState title={online ? "NO ASSETS MATCH" : "START MCP TO BROWSE"}>El catálogo vive en el MCP y se consulta bajo demanda.</PixelEmptyState>}<p className="muted">{total ? `${total} resultados · README y manifests disponibles en assets/folders.` : ""}</p></PixelPanel>;
}
