import { PixelAssetGrid, PixelButton, PixelCommandBar, PixelEmptyState, PixelPanel, PixelPresetStrip } from "@jdsalasc/pixel-ui";
import type { AssetLibraryItemView, AssetLibraryPresetCompositionView, AssetLibraryPresetView } from "../domain/contracts.js";

interface AssetLibraryPanelProps { busy: boolean; online: boolean; restPort?: number; query: string; items: AssetLibraryItemView[]; presets: AssetLibraryPresetView[]; total: number; composition?: AssetLibraryPresetCompositionView | null; onQueryChange(query: string): void; onSearch(): void; onComposePreset?(id: string): void; onGeneratePreset?(id: string): void; }

export function AssetLibraryPanel({ busy, online, restPort, query, items, presets, total, composition, onQueryChange, onSearch, onComposePreset, onGeneratePreset }: AssetLibraryPanelProps) {
  const previewBase = restPort ? `http://127.0.0.1:${restPort}/api/v1/library/items` : "";
  return <PixelPanel title="ASSET LIBRARY" accent="cyan"><p className="muted">Explora assets deterministas y presets de escenas sin cargar todo el catálogo en contexto.</p><div className="asset-library-search"><PixelCommandBar value={query} onValueChange={onQueryChange} placeholder="Search trees, dragons, rain..." aria-label="Search asset library" /><PixelButton tone="cyan" disabled={busy || !online} onClick={onSearch}>{busy ? "SEARCHING..." : "SEARCH LIBRARY"}</PixelButton></div>{presets.length ? <PixelPresetStrip label="Scene presets" options={presets.map((preset) => ({ id: preset.id, title: preset.title, description: preset.description }))} selectedId={composition?.preset.id} onSelect={(id) => onComposePreset?.(id)} disabled={busy || !online || !onComposePreset} /> : null}{composition ? <><p className="muted">PRESET READY · {composition.layers.map((layer) => `${layer.role}:${layer.assetId}`).join(" · ")}</p>{onGeneratePreset ? <div className="tool-runner-actions"><PixelButton tone="amber" disabled={busy || !online} onClick={() => onGeneratePreset(composition.preset.id)}>GENERATE SCENE</PixelButton></div> : null}</> : null}{items.length ? <PixelAssetGrid items={items.map((item) => ({ id: item.id, name: item.title, preview: previewBase ? `${previewBase}/${encodeURIComponent(item.id)}/${item.animationPath ? "animation" : "preview"}` : undefined, detail: `${item.category} · ${item.animationPath ? "GIF" : "PNG"} · ${item.variants.slice(0, 3).join(" · ")}`, status: <small>{item.kind.toUpperCase()}</small> }))} /> : <PixelEmptyState title={online ? "NO ASSETS MATCH" : "START MCP TO BROWSE"}>El catálogo vive en el MCP y se consulta bajo demanda.</PixelEmptyState>}<p className="muted">{total ? `${total} resultados · README y manifests disponibles en assets/folders.` : ""}</p></PixelPanel>;
}
